# Site settings
title: Japan
client:
  name: Eine neue Welt erleben
  link: "http://bit.ly/2ASgXFX"
  link2: "http://bit.ly/2W1X1t9"
core-se-link: https://www.secretescapes.de/aktuelle-angebote
description: >
  Lorem Ipsum

# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/de/japan" # the subpath of your site, e.g. /blog/
img:     "/de/japan/_assets/img"
css:     "/de/japan/_assets/css"
js:      "/de/japan/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed
